name: Docker File CI

'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'Dockerfile'
        lint: 'hadolint'
