name: Docker File CI

'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'debian11/Dockerfile'
        lint: 'hadolint'

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Build Debian Image
      run: docker build . --file debian11/Dockerfile --tag ventor/docker-debian11-ansible:cibuild