name: Docker Push to Hub

'on':
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'debian11/Dockerfile'
        lint: 'hadolint'
